### ISSUE TITLE
Whats app story like featue

### ISSUE THREAD

**Issue by harshkumarkhatri** [ajilo297/Flutter-Dotted-Border#10]
Hey. I have used this in one of my projects where I needed dashed border. 
Now in my other project, I was thinking to use it to show the count of the stories which the user has uploaded, something similar to the WhatsApp story feature.
Is there a way that dashes that are displayed automatically render on the basis of story number?

**Comment by ajilo297** [comment]
Are you sure you are not thinking of a `LinearProgressIndicator` which would be more apt in this case?

**Comment by harshkumarkhatri** [comment]
You are assuming it to be a different use case. 
The use case which I wanted to implement is the one which I have shown in the image attached.
As the user will upload a story, the gaps and the edges for the dotted border should change automatically based on the count of the number of images that are uploaded.
![Screenshot from 2020-08-26 14-42-54](https://user-images.githubusercontent.com/42743629/91285184-82045500-e7aa-11ea-91b0-2425d4c4ad73.png)
This image is from WhatsApp stories. I am thinking of implementing something similar.
Although I found a solution to this which is not very efficient due to the following reasons.
1) It is hard to calculate the edges which are to be made as gaps are also to be changed dynamically based on the number of the images uploaded.
2) If a user has uploaded many images then the calculation becomes complex and the app freezes.
The solution which I found:- https://github.com/feMoraes0/whatsapp-redesign-ui/blob/master/lib/components/status_bar.dart
He has used a variable quantStatus o identify the number of stories but it is not an efficient way.

**Comment by ajilo297** [comment]
[This](https://pub.dev/packages/step_progress_indicator) one can be used to do this.

**Comment by ajilo297** [comment]
It's not worth the hassle to do this with Dotted Border.

**Comment by harshkumarkhatri** [comment]
I hope this helps.
