### ISSUE TITLE
when update to `2.0.0+2`，it will version solving failed with `flutter_html`

### ISSUE THREAD

**Issue by PDieE** [ajilo297/Flutter-Dotted-Border#18]
**Describe the bug**
when update to `2.0.0+2`，it will version solving failed with `flutter_html`

**To Reproduce**
```
dependencies:
  flutter_html: ^2.1.2
  dotted_border: ^2.0.0+2
```

**Expected behavior**
can use dotted_border 2.0.0+2+ and flutter_html  at the same time

**Screenshots**
![image](https://user-images.githubusercontent.com/14084550/154601498-c73605a6-6f18-496a-849f-bf7dd3ac4cda.png)

**Desktop (please complete the following information):**
 - all

**Smartphone (please complete the following information):**
 - all

**Additional context**
```
Running "flutter pub get" in xilaijian_app...                   
Because flutter_svg >=0.23.0 <1.0.0 depends on path_drawing ^0.5.1 and flutter_svg >=0.21.0 <0.23.0 depends on path_drawing ^0.5.0, flutter_svg >=0.21.0 <1.0.0 requires path_drawing ^0.5.0.
And because dotted_border >=2.0.0+2 depends on path_drawing ^1.0.0 and flutter_html >=2.0.0-nullsafety.1 <3.0.0-alpha.1 depends on flutter_svg >=0.22.0 <1.0.0, dotted_border >=2.0.0+2 is incompatible with flutter_html >=2.0.0-nullsafety.1 <3.0.0-alpha.1.
So, because xilaijian_app depends on both flutter_html ^2.1.2 and dotted_border ^2.0.0+2, version solving failed.
pub get failed (1; So, because xilaijian_app depends on both flutter_html ^2.1.2 and dotted_border ^2.0.0+2, version solving failed.)
```

**Comment by yossefEl** [comment]
@hxywuya Indeed, the pre-release flutter_html: ^3.0.0-alpha.5 solved the issue. Thank you!

**Comment by maerlynflagg** [comment]
But after 10 months no new release? will 3.0.0 ever be released?

**Comment by ajilo297** [comment]
Apologies for taking so long to respond.

Upgrading your dependency to `flutter_html: 3.0.0-beta.2` seems to solve the problem
