### ISSUE TITLE
radius does not work

### ISSUE THREAD

**Issue by ChurikiTenna** [ajilo297/Flutter-Dotted-Border#25]
**Describe the bug**
radius does not work.

**To Reproduce**
Run code below
```
DottedBorder(
      color: Color.fromARGB(255, 134, 129, 129), // 点線の色
      radius: Radius.circular(12),
      dashPattern: [6.0,4.0],
      strokeWidth: 3.0,
      strokeCap: StrokeCap.round,
      child: ClipRRect(
        borderRadius: BorderRadius.all(Radius.circular(12)),
        child: child),
    )
```

**Expected behavior**
Corner rounded

**Screenshots**
![IMG_4D5C44F26878-1](https://user-images.githubusercontent.com/52132649/205036688-ee1fc688-d9da-4976-b802-a58742bd8b6d.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser non
 - Version 2.0.0+3

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS
 - Browser non
 - Version 16.0

**Comment by ajilo297** [comment]
Thanks for raising the issue.
I know this is not intuitive and I am trying to find some time to fix it.

BorderRadius will affect the border type only if the `borderType` is of type `BorderType.RRect`.

So your code would become something like this

``` dart
DottedBorder(
  color: const Color.fromARGB(255, 134, 129, 129),
  borderType: BorderType.RRect, // <- You need this
  radius: const Radius.circular(12),
  dashPattern: const [6.0, 4.0],
  strokeWidth: 3.0,
  strokeCap: StrokeCap.round,
  child: ClipRRect(
    borderRadius:
        const BorderRadius.all(Radius.circular(12)),
    child: child,
  ),
)
```
