### ISSUE TITLE
Provide a means to override StackFit.loose

### ISSUE THREAD

**Issue by lclaesen** [ajilo297/Flutter-Dotted-Border#28]
A big thanks for your package: it saved us the time and trouble of having to develop a custom border ourselves.

It would greatly improve the usability of your widget, if it would allow to control the constraints that `DottedBorder` would pass to its child widget. Currently, the inner stack always loosens the constraints passed to the child (the default value of `Stack.fit`); that might be what some of the users want, but certainly not wat all of them want to happen. In our particular case, we want `DottedBorder.child` to respect a minimal height imposed on the `DottedBorder` widget itself -- something that the Stack allows by setting it's `fit` property to `StackFit.passthrough`.

**Comment by ajilo297** [comment]
This should be fixed by 2cd8eca89a7e779cc22af6278550b8541438386f

**Comment by lclaesen** [comment]
Thanks a lot, @ajilo297. Works like a charm.
