### ISSUE TITLE
Border being drawn before child widget causing it to disappear beneath it when adding padding to borderPadding property

### ISSUE THREAD

**Issue by DeadlockOfDeath** [ajilo297/Flutter-Dotted-Border#32]
I was using your package, and I wanted to add a border around a TextField. I was going for something like this where the dashed lines are inside the child widget:
![TextField](https://github.com/ajilo297/Flutter-Dotted-Border/assets/133504785/cde61c23-80d3-447b-b510-a3be3185eafa)
I figured out you can use the borderPadding property to control this, but when I add the padding the border goes beneath the child widget and disappears. This can be easily fixed if you just swap the two child widgets of the stack, I tested it already and it works.
![swap](https://github.com/ajilo297/Flutter-Dotted-Border/assets/133504785/ab569eef-fda4-45e4-991e-0c305b11fd63)
Is there a reason why it is like this?

**Comment by ajilo297** [comment]
@DeadlockOfDeath That's a good idea actually. I will consider doing it in the next iteration.

**Comment by DeadlockOfDeath** [comment]
Thanks for looking at this. I am a beginner at Flutter and looking at your CustomPainter source code is educational for me.

**Comment by ajilo297** [comment]
@DeadlockOfDeath Let's keep this issue open until I can make the change. In the meantime, if you can create a PR, that would help as well.

**Comment by DeadlockOfDeath** [comment]
I don't really know how GitHub works to be honest but I'll try.

**Comment by DeadlockOfDeath** [comment]
I just made a pull request, this is my first time. Did I do it right?

**Comment by ajilo297** [comment]
Closed by #39
