### ISSUE TITLE
Setting dashPattern: [0,0] or [0] crashes hot reload, and requires restart of simulator + Android Studio

### ISSUE THREAD

**Issue by Nailer** [ajilo297/Flutter-Dotted-Border#4]
In an attempt to use the same widget for a solid border and dashed border, I stumbled into a weird bug where setting dashPattern to [0,0] or [0] brings down the whole iOS simulator + Android studio. For anything to work again, I have to restart both the simulator and Android studio.

I haven't tried much with other devices, but I assume something similar will happen.

I have a widget where I want the border to be dotted in one state, but solid in another. 
Is there a safe way of setting a non-dashed border other than using a different widget altogether?

**Comment by ajilo297** [comment]
I have now added a check to make sure that the `dashPattern` property is considered invalid if it is an array of zeroes.

As an aside, to get a solid border, you should use a `dashPattern` as `[a, 0]` where `a > 0`.

Closing this issue, as I think this resolves that specific problem.
