### ISSUE TITLE
Doesn't work on Web

### ISSUE THREAD

**Issue by agordeev** [ajilo297/Flutter-Dotted-Border#7]
The package claims it's compatible with Web, but unfortunately it doesn't. `path_drawing`'s `dashPath` method throws `Unimplemented` error.

**Comment by agordeev** [comment]
A related issue: https://github.com/flutter/flutter/issues/48386
It'd be good if we can remove Web as a target platform for this package until the method is implemented for Web.

**Comment by ajilo297** [comment]
I do not know if/how Web can be removed as a target platform. Meanwhile, I could update the Readme to say it does not support the web builds as of now.

Thanks for pointing out it does not work for web though.
